from fastapi import FastAPI
import random

app = FastAPI()

# Sample facts
facts = [
    "Bananas are berries, but strawberries are not.",
    "A day on Venus is longer than a year on Venus.",
    "Honey never spoils—it has been found in ancient tombs still edible.",
    "Octopuses have three hearts.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Water can boil and freeze at the same time under the right conditions.",
    "A group of flamingos is called a 'flamboyance'.",
    "The Eiffel Tower can grow taller in the summer due to heat expansion.",
    "Sloths can hold their breath longer than dolphins.",
    "The inventor of the Frisbee was turned into a Frisbee after he died.",
    "The heart beats about 100,000 times a day.",
    "There are more trees on Earth than stars in the Milky Way.",
    "The average cloud weighs about a million pounds.",
    "Wombat poop is cube-shaped.",
    "The unicorn is Scotland’s national animal.",
    "Your bones are about five times stronger than steel of the same density.",
    "The shortest war in history lasted 38 to 45 minutes.",
    "A shrimp’s heart is located in its head.",
    "An adult human has about 206 bones, but babies are born with around 300.",
    "The name 'Google' comes from a misspelling of 'googol', which means 10¹⁰⁰.",
    "The word 'alphabet' comes from the first two Greek letters: alpha and beta.",
    "Some turtles can breathe through their butts.",
    "A jiffy is an actual unit of time, about 1/100th of a second.",
    "The world's longest hiccup spree lasted 68 years.",
    "Hot water freezes faster than cold water in some conditions (Mpemba effect).",
    "The Great Wall of China isn’t visible from space with the naked eye.",
    "Peanuts aren’t nuts; they’re legumes.",
    "The human nose can detect over a trillion different scents.",
    "A cockroach can live for weeks without its head.",
    "The letter 'E' is the most common letter in English.",
    "A day on Earth isn’t exactly 24 hours—it’s about 23 hours, 56 minutes, and 4 seconds.",
    "The dot over the lowercase 'i' and 'j' is called a tittle.",
    "The speed of a sneeze can reach up to 100 mph.",
    "Cows have best friends and get stressed when separated.",
    "Sharks existed before trees.",
    "Butterflies can taste with their feet.",
    "There's a species of jellyfish that is biologically immortal.",
    "The human body has about 37.2 trillion cells.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "Bees can recognize human faces.",
    "An octopus has nine brains and blue blood.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "A group of crows is called a 'murder'.",
    "Humans share about 60 percent of their DNA with bananas.",
    "The first oranges weren’t orange—they were green.",
    "A flea can jump 350 times its body length.",
    "Avocados are berries, but raspberries are not.",
    "The national animal of Canada is the beaver.",
    "Vending machines kill more people per year than sharks.",
    "Sea otters hold hands while sleeping to keep from drifting apart.",
    "A crocodile can't stick out its tongue.",
    "The longest word in English has 189,819 letters and takes over 3 hours to say.",
    "Earth is the only planet in the solar system not named after a god.",
    "The word 'strengths' is the longest English word with only one vowel.",
    "A blue whale’s heart is the size of a small car.",
    "The fingerprints of a koala are almost indistinguishable from a human's.",
    "Alaska is the westernmost, easternmost, and northernmost state in the U.S.",
    "A full NASA spacesuit costs about $12 million.",
    "The moon is slowly moving away from Earth at a rate of 1.5 inches per year.",
    "A jellyfish is about 95% water.",
    "Only female mosquitoes bite.",
    "The smell of freshly-cut grass is actually a plant distress signal.",
    "The human brain generates enough electricity to power a small light bulb.",
    "The probability of a deck of cards being shuffled into the same order twice is almost zero.",
    "Giraffes have the same number of neck vertebrae as humans (seven).",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "Ants don’t have lungs.",
    "Snakes can sense earthquakes days before they happen.",
    "A day on Mars is only 37 minutes longer than a day on Earth.",
    "The fear of long words is called 'hippopotomonstrosesquippedaliophobia'.",
    "The electric eel can produce a shock of up to 600 volts.",
    "A teaspoon of honey is the life’s work of 12 bees.",
    "Jelly beans take about 21 days to make.",
    "Cleopatra lived closer in time to the first moon landing than to the building of the Great Pyramid.",
    "Bubble wrap was originally invented to be wallpaper.",
    "The shortest sentence in English is 'I am'.",
    "Penguins propose to their mates with a pebble.",
    "There's a basketball court on the top floor of the U.S. Supreme Court called 'the highest court in the land'.",
    "If you shuffled a deck of cards, the order you get has probably never existed before in history.",
    "Hawaii moves 4 inches closer to Japan every year.",
    "The current population of Earth represents only about 7 percent of all humans who have ever lived.",
    "An astronaut's height can increase by up to two inches in space.",
    "Venus is the hottest planet in the solar system, even though Mercury is closer to the Sun.",
    "Bananas grow upside-down compared to how they are typically displayed in stores.",
    "The word 'robot' comes from a Czech word meaning 'forced labor'.",
    "A cat has 32 muscles in each ear.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Ketchup was once sold as medicine.",
    "There's a town in Norway where the sun doesn’t set for about two and a half months in summer.",
    "The average lifespan of a taste bud is about ten days.",
    "A group of porcupines is called a 'prickle'.",
    "Frogs can freeze solid in winter and thaw out in spring, alive.",
    "The Guinness World Record for the longest time spent awake is 11 days.",
    "In 1518, a 'dancing plague' caused people to dance uncontrollably for days.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "A strawberry isn't technically a berry, but a watermelon is.",
    "The wood frog can hold its pee for up to eight months.",
    "There is more real lemon juice in Lemon Pledge furniture polish than in Country Time Lemonade.",
    "The dot on a dice is called a 'pip'.",
    "An ant can survive being microwaved.",
    "The sound a giraffe makes is almost never heard because it's too low for human ears.",
    "If you cut a starfish in half, it can regenerate into two starfish.",
    "Your stomach gets a new lining every three to four days to prevent it from digesting itself.",
    "There's a species of fish that can climb trees.",
    "Octopuses can change color in less than a second to blend into their surroundings.",
    "A hippo’s milk is pink.",
    "The word 'muscle' comes from a Latin word meaning 'little mouse' because people thought biceps looked like mice under the skin.",
    "The world’s quietest room is so silent that people can hear their own blood flowing.",
    "The average raindrop falls at about 20 mph.",
    "Mount Everest is not the tallest mountain—Mauna Kea is taller when measured from base to peak.",
    "Cats have a special reflective layer behind their retinas called the tapetum lucidum, which helps them see in the dark.",
    "Male seahorses are the ones that carry and give birth to babies.",
    "The smell of chocolate increases theta brain waves, which trigger relaxation.",
    "Apples float because they are 25 percent air.",
    "The average lifespan of a housefly is about 28 days.",
    "The total weight of ants on Earth is roughly equal to the total weight of humans.",
    "Goosebumps are a leftover trait from when humans had thicker body hair for warmth.",
    "If you lift a kangaroo’s tail off the ground, it can't hop.",
    "There’s enough gold in Earth’s core to coat the planet in a layer 1.5 feet thick.",
    "The average person has about 100,000 hairs on their head.",
    "The blue whale is the loudest animal on Earth.",
    "You can't hum while holding your nose.",
    "The Eiffel Tower shrinks by about six inches in the winter.",
    "The human body contains about 0.2 milligrams of gold, mostly in the blood.",
    "The word 'quiz' was originally a bet.",
    "A giraffe's neck is too short to reach the ground, so it has to spread its legs apart to drink water.",
    "Hummingbirds are the only birds that can fly backwards.",
    "A cloud can weigh more than a million pounds.",
    "Coca-Cola would be green if coloring wasn’t added to it.",
    "In 1969, two amateur cyclists became the first people to ride a bicycle to the top of Mount Everest."
    "The fastest recorded speed of a sneeze is 103 miles per hour.",
    "Sharks have been around longer than trees, appearing 400 million years ago.",
    "A sneeze can travel up to 100 miles per hour.",
    "There’s a species of jellyfish that can regenerate its cells and potentially live forever.",
    "The shortest commercial flight in the world is only 57 seconds long.",
    "There’s a type of mushroom that can glow in the dark.",
    "The longest hiccup streak lasted for 68 years.",
    "The longest English word with only one vowel is 'strengths'.",
    "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in the heat.",
    "A snail can sleep for three years.",
    "A crocodile cannot stick out its tongue.",
    "A human’s nose can detect over 1 trillion different scents.",
    "The largest desert in the world isn’t the Sahara—it's Antarctica.",
    "An octopus has three hearts and blue blood.",
    "The average person spends six months of their lifetime waiting for red lights to turn green.",
    "In some parts of the world, it’s illegal to step on money.",
    "The tongue is the only muscle in the human body that is attached from one end only.",
    "In 1518, a 'dancing plague' broke out in France, where people danced uncontrollably for weeks.",
    "Polar bear skin is black, even though their fur is white.",
    "A bolt of lightning can heat the air to 30,000 Kelvin, five times hotter than the surface of the sun.",
    "The Great Wall of China is not visible from space without aid.",
    "The national animal of Scotland is the unicorn.",
    "Venus spins in the opposite direction to most other planets.",
    "An astronaut’s height can increase by up to 2 inches in space.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "The largest volcano in the solar system is on Mars and is called Olympus Mons.",
    "A full NASA spacesuit costs about $12 million.",
    "Cleopatra lived closer to the first moon landing than the construction of the Great Pyramid.",
    "The shortest war in history lasted between 38 and 45 minutes.",
    "The fear of long words is called hippopotomonstrosesquippedaliophobia.",
    "You can't hum while holding your nose.",
    "The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.",
    "The word 'dinosaur' means 'terrible lizard' in Greek.",
    "A jiffy is an actual unit of time equal to 1/100th of a second.",
    "Honey never spoils, and archaeologists have found pots of honey in ancient Egyptian tombs that are still edible.",
    "The shortest sentence in English is 'I am.'",
    "The human brain has around 100 billion neurons.",
    "The Eiffel Tower can shrink by as much as 6 inches in winter due to cold temperatures.",
    "The longest recorded time a human has spent awake is 11 days.",
    "An adult human body is made up of approximately 37.2 trillion cells.",
    "The world's longest hiccup streak lasted for 68 years.",
    "There’s a town in Norway where the sun doesn’t set for about two and a half months in summer.",
    "In Japan, there is a museum dedicated to rocks that look like faces.",
    "Sharks do not get cancer.",
    "A group of flamingos is called a flamboyance.",
    "A blue whale’s heart is the size of a small car.",
    "An adult human has about 206 bones, but babies are born with about 300.",
    "The unicorn is the national animal of Scotland.",
    "The moon is slowly drifting away from Earth at a rate of about 1.5 inches per year.",
    "Bananas grow upside-down compared to how they are displayed in stores.",
    "Peanuts are not actually nuts; they are legumes.",
    "Your bones are about five times stronger than steel of the same density.",
    "The average person’s heartbeat is about 100,000 times per day.",
    "If you cut a starfish in half, each half can grow into a new starfish.",
    "There is more gold in Earth’s core than in all the human history’s gold combined.",
    "Avocados are actually berries, but raspberries are not.",
    "An octopus has three hearts and blue blood.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The longest recorded sneeze lasted for 976 days.",
    "A full moon on Halloween only happens once every 19 years.",
    "The dot over the lowercase 'i' and 'j' is called a tittle.",
    "The longest hiccup streak lasted 68 years.",
    "The world’s largest snowflake was 15 inches wide.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "Sharks have been around longer than trees, existing for 400 million years.",
    "Humans share 60% of their DNA with bananas.",
    "The Eiffel Tower was initially intended to be a temporary structure.",
    "In 1969, two amateur cyclists became the first people to ride a bicycle to the top of Mount Everest.",
    "Cows have best friends and get stressed when separated.",
    "The average human body contains enough carbon to fill 9,000 pencils.",
    "Coca-Cola would be green if coloring wasn’t added.",
    "Penguins propose to their mates with a pebble.",
    "The longest living animal in the world is the ocean quahog clam, which can live for over 500 years.",
    "A human's nose can detect over 1 trillion different scents.",
    "A group of crows is called a murder.",
    "The longest time spent awake is 11 days.",
    "Mount Everest is not the tallest mountain when measured from base to peak; Mauna Kea is.",
    "There's a species of fish that can climb trees.",
    "The human brain is sometimes more active while asleep than while awake.",
    "A giraffe’s neck is too short to reach the ground, so it has to spread its legs apart to drink.",
    "Male seahorses are the ones that carry and give birth to babies.",
    "The world’s quietest room is so silent that people can hear their own blood flowing.",
    "The Eiffel Tower shrinks by about 6 inches in the winter due to temperature changes.",
    "Octopuses can change color in less than a second to blend into their surroundings.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "The sound a giraffe makes is almost never heard because it’s too low-pitched for humans to hear.",
    "The blue whale is the loudest animal on Earth.",
    "Ants don’t have lungs.",
    "Only female mosquitoes bite.",
    "The fear of long words is called 'hippopotomonstrosesquippedaliophobia'.",
    "There’s a species of jellyfish that is biologically immortal.",
    "A kangaroo’s tail is so powerful that it can support its entire body weight.",
    "Giraffes only need to sleep for about 20 minutes to two hours a day.",
    "The world’s largest desert is Antarctica, not the Sahara.",
    "Hummingbirds are the only birds that can fly backwards.",
    "In Japan, vending machines sell hot meals.",
    "A whale's tongue weighs as much as an elephant.",
    "It rains diamonds on Jupiter and Saturn.",
    "The longest time someone has gone without sleep is 11 days.",
    "A whale's heart can weigh as much as a car.",
    "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    "The average person spends six months of their lifetime waiting for red lights to turn green.",
    "The average raindrop falls at a speed of 20 miles per hour.",
    "Cleopatra lived closer in time to the moon landing than to the Great Pyramid's construction.",
    "In some places, people celebrate a holiday called 'Giraffe Day'.",
    "Your bones are about five times stronger than steel of the same density."
    "The longest recorded time a person has been awake is 11 days.",
    "The shortest commercial flight in the world lasts only 57 seconds.",
    "An adult human has 206 bones, but babies have around 300 bones.",
    "Sharks are older than trees, having existed for over 400 million years.",
    "The heart of a blue whale can weigh as much as a car.",
    "The Eiffel Tower can grow up to 15 cm taller in the summer due to the heat expansion of iron.",
    "A crocodile can't stick its tongue out.",
    "The average person will walk the equivalent of five times around the world in their lifetime.",
    "Wombat poop is cube-shaped.",
    "The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.",
    "The longest hiccup spree lasted 68 years.",
    "A jiffy is a real unit of time, equal to 1/100th of a second.",
    "A shrimp's heart is located in its head.",
    "The Great Wall of China isn't visible from space with the naked eye.",
    "An octopus has three hearts and blue blood.",
    "Humans share 60% of their DNA with bananas.",
    "An astronaut's height can increase by 2 inches in space.",
    "Honey never spoils and has been found in ancient tombs still edible.",
    "Sloths can hold their breath for up to 40 minutes.",
    "Cleopatra lived closer in time to the first moon landing than to the construction of the Great Pyramid.",
    "There’s a species of jellyfish that is biologically immortal.",
    "Peanuts are technically legumes, not nuts.",
    "The average human body contains around 37.2 trillion cells.",
    "The longest recorded time someone has gone without sleep is 11 days.",
    "The Eiffel Tower was originally intended to be a temporary structure.",
    "In 1969, two amateur cyclists became the first to ride a bicycle to the top of Mount Everest.",
    "There’s enough gold in Earth's core to cover the entire planet in a 1.5-foot thick layer.",
    "The world's longest hiccup spree lasted 68 years.",
    "Male seahorses are the ones that carry and give birth to babies.",
    "An octopus can change color in less than a second to blend into its surroundings.",
    "A cat has 32 muscles in each ear.",
    "If you cut a starfish in half, it can regenerate into two starfish.",
    "A giraffe’s neck has the same number of vertebrae as a human’s neck (seven).",
    "The moon is slowly drifting away from Earth at a rate of 1.5 inches per year.",
    "A group of flamingos is called a 'flamboyance'.",
    "The speed of a sneeze can reach up to 100 miles per hour.",
    "The word 'robot' comes from the Czech word for 'forced labor'.",
    "A blue whale’s tongue weighs as much as an elephant.",
    "The longest word in English has 189,819 letters.",
    "A cockroach can live for weeks without its head.",
    "Bananas are technically berries, but strawberries are not.",
    "There are more trees on Earth than stars in the Milky Way.",
    "A flea can jump 350 times its body length.",
    "Your stomach gets a new lining every 3-4 days to prevent it from digesting itself.",
    "Cows have best friends and get stressed when they are separated.",
    "The average raindrop falls at 20 miles per hour.",
    "An adult human has about 100,000 hairs on their head.",
    "The dot above a lowercase 'i' and 'j' is called a tittle.",
    "If you shuffle a deck of cards, the order you're dealt has probably never existed before in the history of the universe.",
    "The human body generates enough electricity to power a small light bulb.",
    "The world's longest hiccup streak lasted 68 years.",
    "A jiffy is a real unit of time, equal to 1/100th of a second.",
    "In 1518, a 'dancing plague' broke out in France, where people danced uncontrollably for weeks.",
    "The shortest sentence in English is 'I am'.",
    "The human nose can detect over a trillion different scents.",
    "There are more stars in the universe than grains of sand on all of Earth’s beaches.",
    "The largest desert in the world isn’t the Sahara—it’s Antarctica.",
    "The Great Wall of China is not visible from space without aid.",
    "The blue whale is the loudest animal on Earth.",
    "An astronaut’s height can increase by up to two inches in space due to the lack of gravity.",
    "There are more stars in the sky than grains of sand on Earth.",
    "The national animal of Canada is the beaver.",
    "The Eiffel Tower can shrink by 6 inches in winter.",
    "Avocados are technically berries, but raspberries are not.",
    "Sharks existed before trees, appearing 400 million years ago.",
    "The longest hiccup streak lasted for 68 years.",
    "The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.",
    "The moon is slowly drifting away from Earth at a rate of 1.5 inches per year.",
    "Venus is the hottest planet in the solar system, even though Mercury is closer to the Sun.",
    "Bananas grow upside down compared to how they are typically displayed in stores.",
    "Peanuts are not actually nuts; they are legumes.",
    "Your bones are about five times stronger than steel of the same density.",
    "The average person’s heartbeat is about 100,000 times per day.",
    "If you cut a starfish in half, each half can grow into a new starfish.",
    "There is more gold in Earth’s core than in all the human history’s gold combined.",
    "Avocados are actually berries, but raspberries are not.",
    "An octopus has three hearts and blue blood.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "The Great Wall of China isn't visible from space with the naked eye.",
    "The longest recorded sneeze lasted for 976 days.",
    "A full moon on Halloween only happens once every 19 years.",
    "The dot on a dice is called a 'pip'.",
    "The longest living animal in the world is the ocean quahog clam, which can live for over 500 years.",
    "A human's nose can detect over 1 trillion different scents.",
    "A group of crows is called a murder.",
    "The longest time spent awake is 11 days.",
    "Mount Everest is not the tallest mountain when measured from base to peak; Mauna Kea is.",
    "There's a species of fish that can climb trees.",
    "The human brain is sometimes more active while asleep than while awake.",
    "A giraffe’s neck is too short to reach the ground, so it has to spread its legs apart to drink.",
    "Male seahorses are the ones that carry and give birth to babies.",
    "The world’s quietest room is so silent that people can hear their own blood flowing.",
    "The Eiffel Tower shrinks by about 6 inches in the winter due to temperature changes.",
    "Octopuses can change color in less than a second to blend into their surroundings.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "The sound a giraffe makes is almost never heard because it’s too low-pitched for humans to hear.",
    "The blue whale is the loudest animal on Earth.",
    "Ants don’t have lungs.",
    "Only female mosquitoes bite.",
    "The fear of long words is called 'hippopotomonstrosesquippedaliophobia'.",
    "There’s a species of jellyfish that is biologically immortal.",
    "A kangaroo’s tail is so powerful that it can support its entire body weight.",
    "Giraffes only need to sleep for about 20 minutes to two hours a day.",
    "The world’s largest desert is Antarctica, not the Sahara.",
    "Hummingbirds are the only birds that can fly backwards.",
    "In Japan, vending machines sell hot meals.",
    "A whale's tongue weighs as much as an elephant.",
    "It rains diamonds on Jupiter and Saturn.",
    "The longest time someone has gone without sleep is 11 days.",
    "A whale's heart can weigh as much as a car.",
    "There are more stars in the universe than grains of sand on all the beaches on Earth.",
    "The average person spends six months of their lifetime waiting for red lights to turn green.",
    "The average raindrop falls at 20 miles per hour.",
    "Cleopatra lived closer in time to the moon landing than to the Great Pyramid's construction.",
    "In some places, people celebrate a holiday called 'Giraffe Day'.",
    "Your bones are about five times stronger than steel of the same density."
    "A cockroach can live for weeks without its head.",
    "The longest hiccup streak lasted 68 years.",
    "Sharks existed before trees, having been around for more than 400 million years.",
    "Honey never spoils, and jars of honey have been found in ancient tombs that are still edible.",
    "The longest sneeze lasted 976 days.",
    "A shrimp’s heart is located in its head.",
    "Bananas are technically berries, but strawberries are not.",
    "There are more stars in the universe than grains of sand on all of Earth's beaches.",
    "A group of flamingos is called a 'flamboyance'.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The Eiffel Tower can grow up to 15 cm taller in the summer due to heat expansion.",
    "An octopus has three hearts and blue blood.",
    "The longest commercial flight in the world lasts 18 hours.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "You can't hum while holding your nose.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "The shortest sentence in English is 'I am'.",
    "The world’s largest desert is Antarctica, not the Sahara.",
    "There is a species of jellyfish that is biologically immortal.",
    "A cat has 32 muscles in each ear.",
    "The average cloud weighs about a million pounds.",
    "An astronaut’s height can increase by up to 2 inches in space.",
    "Venus is the hottest planet in the solar system, even though Mercury is closer to the Sun.",
    "The word 'robot' comes from a Czech word meaning 'forced labor'.",
    "A giraffe’s neck has the same number of vertebrae as a human's neck (seven).",
    "The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.",
    "The moon is slowly drifting away from Earth at a rate of about 1.5 inches per year.",
    "The Eiffel Tower shrinks by about 6 inches during the winter.",
    "The longest time spent awake is 11 days.",
    "Cleopatra lived closer in time to the first moon landing than to the building of the Great Pyramid of Giza.",
    "The total weight of all the ants on Earth is roughly equal to the total weight of all the humans.",
    "A crocodile can't stick out its tongue.",
    "An octopus can change color in less than a second to blend into its surroundings.",
    "A blue whale’s tongue weighs as much as an elephant.",
    "The shortest commercial flight in the world lasts only 57 seconds.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The human brain generates enough electricity to power a small light bulb.",
    "The first oranges weren’t orange—they were green.",
    "Sloths can hold their breath for up to 40 minutes.",
    "There are more stars in the universe than grains of sand on Earth.",
    "The letter 'E' is the most common letter in the English language.",
    "Cows have best friends and get stressed when they are separated.",
    "The world’s quietest room is so silent that people can hear their own blood flowing.",
    "A cockroach can live for weeks without its head.",
    "There’s a species of fish that can climb trees.",
    "A blue whale’s heart weighs as much as a car.",
    "Male seahorses are the ones that carry and give birth to babies.",
    "The moon is slowly drifting away from Earth at a rate of about 1.5 inches per year.",
    "Ants don’t have lungs.",
    "If you cut a starfish in half, it can regenerate into two starfish.",
    "The shortest war in history lasted only 38 minutes.",
    "Butterflies can taste with their feet.",
    "The longest time a person has gone without sleep is 11 days.",
    "The Eiffel Tower was originally intended to be a temporary structure.",
    "The human nose can detect over a trillion different scents.",
    "A giraffe's neck has the same number of vertebrae as a human’s neck (seven).",
    "The average raindrop falls at a speed of about 20 mph.",
    "There’s a basketball court on the top floor of the U.S. Supreme Court building called 'the highest court in the land.'",
    "The average person will walk the equivalent of five times around the world in their lifetime.",
    "Cleopatra lived closer in time to the moon landing than to the building of the Great Pyramid of Giza.",
    "The world’s largest desert is Antarctica, not the Sahara.",
    "The first oranges weren't orange—they were green.",
    "The average person has about 100,000 hairs on their head.",
    "An astronaut's height can increase by 2 inches in space.",
    "The fear of long words is called 'hippopotomonstrosesquippedaliophobia.'",
    "The longest word in English has 189,819 letters.",
    "A jiffy is a real unit of time, equal to 1/100th of a second.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Sharks have been around for more than 400 million years.",
    "A cat's nose is as unique as a human's fingerprint.",
    "Avocados are technically berries, but raspberries are not.",
    "The Eiffel Tower was intended to be a temporary structure.",
    "There’s a species of jellyfish that is biologically immortal.",
    "The average human body contains around 37.2 trillion cells.",
    "The longest time a human has gone without sleep is 11 days.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The total weight of ants on Earth is roughly equal to the total weight of humans.",
    "In some places, people celebrate a holiday called 'Giraffe Day.'",
    "Bananas are berries, but strawberries are not.",
    "The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.",
    "The Great Wall of China is not visible from space without aid.",
    "The blue whale's heart is the size of a small car.",
    "There are more stars in the universe than grains of sand on Earth's beaches.",
    "There’s enough gold in Earth’s core to cover the entire planet in a 1.5-foot-thick layer."
    "A giraffe's neck contains the same number of vertebrae as a human's neck—seven.",
    "The total weight of all ants on Earth is roughly equal to the total weight of all humans.",
    "The longest time a person has spent awake is 11 days.",
    "The world’s largest desert is Antarctica, not the Sahara.",
    "There’s a basketball court on the top floor of the U.S. Supreme Court building, known as 'the highest court in the land.'",
    "Sharks have existed for over 400 million years, even before trees.",
    "The Eiffel Tower grows by about 6 inches during the summer because of thermal expansion.",
    "The moon is slowly moving away from Earth at a rate of 1.5 inches per year.",
    "Sloths can hold their breath for up to 40 minutes underwater.",
    "The fear of long words is called 'hippopotomonstrosesquippedaliophobia.'",
    "The first oranges were green, not orange.",
    "The word 'robot' comes from a Czech word meaning 'forced labor.'",
    "A hippo’s milk is pink.",
    "Bananas are technically berries, while strawberries are not.",
    "The Eiffel Tower was supposed to be a temporary structure for the 1889 World's Fair.",
    "Some species of jellyfish are biologically immortal and can revert to their juvenile form.",
    "The Great Wall of China is not visible from space without aid.",
    "The human nose can distinguish over 1 trillion different smells.",
    "The blue whale’s heart is the size of a small car.",
    "An octopus has three hearts and blue blood.",
    "There is a species of fish that can climb trees.",
    "A group of flamingos is called a 'flamboyance'.",
    "The first time humans stepped on the moon was in 1969, 2,000 years after the construction of the Great Pyramid of Giza.",
    "A flea can jump 350 times its body length.",
    "There’s enough gold in Earth’s core to cover the entire planet in a 1.5-foot-thick layer.",
    "The longest recorded hiccuping spree lasted 68 years.",
    "In some places, people celebrate a holiday called 'Giraffe Day.'",
    "A group of crows is called a 'murder'.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet—alpha and beta.",
    "Octopuses can change color and texture in less than a second to blend into their surroundings.",
    "A shrimp’s heart is located in its head.",
    "The dot over the lowercase 'i' and 'j' is called a tittle.",
    "A cat has 32 muscles in each ear.",
    "A group of porcupines is called a 'prickle'.",
    "A bolt of lightning can contain enough energy to toast 100,000 slices of bread.",
    "The moon is moving away from Earth at about 1.5 inches per year.",
    "The average cloud weighs about a million pounds.",
    "Bananas grow upside-down compared to how they are typically displayed in stores.",
    "Venus is the hottest planet in the solar system, even though Mercury is closer to the Sun.",
    "The shortest war in history lasted 38 to 45 minutes.",
    "Water can boil and freeze at the same time under the right conditions.",
    "The word 'muscle' comes from a Latin word meaning 'little mouse' because people thought biceps looked like mice under the skin.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "The longest word in English has 189,819 letters and takes over 3 hours to say.",
    "Wombat poop is cube-shaped.",
    "There’s a town in Norway where the sun doesn’t set for about two and a half months in summer.",
    "There’s a species of fish that can climb trees.",
    "A jiffy is a real unit of time, equal to 1/100th of a second.",
    "The average human body contains about 37.2 trillion cells.",
    "The longest time a human has gone without sleep is 11 days.",
    "Cleopatra lived closer in time to the first moon landing than to the building of the Great Pyramid.",
    "Sharks existed before trees, having been around for over 400 million years.",
    "The longest recorded flight of a chicken lasted 13 seconds.",
    "The first oranges weren’t orange—they were green.",
    "Octopuses have three hearts.",
    "The longest commercial flight in the world lasts 18 hours.",
    "The Eiffel Tower shrinks by about 6 inches in the winter.",
    "The word 'robot' comes from the Czech word for 'forced labor'.",
    "The human brain generates enough electricity to power a small light bulb.",
    "The world’s quietest room is so silent that people can hear their own blood flowing.",
    "Male seahorses are the ones that give birth to babies.",
    "The average person walks the equivalent of five times around the world in their lifetime.",
    "The total weight of ants on Earth is roughly equal to the total weight of all humans.",
    "The moon is moving away from Earth at a rate of 1.5 inches per year.",
    "The average lifespan of a taste bud is about 10 days.",
    "There's a species of jellyfish that is biologically immortal.",
    "The word 'strengths' is the longest word in the English language with only one vowel.",
    "If you shuffled a deck of cards, the order you get has probably never existed before in history.",
    "A giraffe’s tongue is about 18 inches long.",
    "In 1518, a 'dancing plague' caused people to dance uncontrollably for days.",
    "There’s a species of jellyfish that is biologically immortal.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "You can’t hum while holding your nose.",
    "A jiffy is an actual unit of time, about 1/100th of a second.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "A cat's nose is as unique as a human's fingerprint.",
    "A group of flamingos is called a 'flamboyance'.",
    "The longest word in English has 189,819 letters and takes over 3 hours to say.",
    "The average raindrop falls at about 20 mph.",
    "The letter 'E' is the most common letter in the English language.",
    "The blue whale is the loudest animal on Earth.",
    "A jellyfish is about 95% water.",
    "Sharks existed before trees.",
    "Bananas are berries, but raspberries are not.",
    "There are more stars in the universe than grains of sand on all of Earth's beaches."
    "The U.S. government once tested LSD on unknowing citizens in a project called MKUltra.",
    "A major pharmaceutical company once sold heroin as a cough suppressant.",
    "In 1971, a group of FBI agents infiltrated civil rights movements and activist groups to spy on them.",
    "Coca-Cola once included cocaine in its original recipe.",
    "The CIA helped fund and protect cocaine trafficking in the 1980s during the Iran-Contra affair.",
    "During World War II, the U.S. government secretly experimented on African-American men with syphilis, without their knowledge, in the Tuskegee Study.",
    "Many large corporations intentionally make products with planned obsolescence to force consumers to buy replacements.",
    "In the early 2000s, Monsanto pushed genetically modified crops without fully disclosing the potential health risks.",
    "The Pentagon Papers revealed that the U.S. government lied to the public about the true reasons for involvement in the Vietnam War.",
    "In the 1980s, the U.S. government secretly sold weapons to Iran to fund Contra rebels in Nicaragua.",
    "The U.S. government was once involved in creating the conditions that allowed the rise of ISIS in the Middle East.",
    "Big tobacco companies knowingly misled the public about the dangers of smoking for decades, despite internal knowledge of the health risks.",
    "Many of the fast food chains use factory farms that abuse animals and engage in environmental destruction.",
    "The U.S. Army used to conduct secret biological warfare tests on its own citizens during the Cold War.",
    "Throughout history, powerful elites have used control of education and media to manipulate public perception.",
    "In the 1930s, the U.S. government sent Jews fleeing Nazi Germany back to Europe, where many died in the Holocaust.",
    "For decades, the U.S. government concealed the fact that nuclear testing was causing health problems for nearby residents.",
    "The U.S. government was involved in a covert operation to destabilize the government of Iran in 1953, leading to decades of conflict.",
    "Many pharmaceutical companies have been found guilty of hiding negative research results in favor of profits.",
    "Large corporations like Walmart and Amazon are accused of exploiting labor in developing countries and avoiding taxes in the U.S.",
    "The U.S. government conducted secret radiation experiments on its own citizens, including pregnant women and children.",
    "Corporations have been caught influencing lawmakers to pass laws that benefit their profit margins, even when it harms the public.",
    "Many fossil fuel companies fund climate change denial campaigns, despite the overwhelming evidence of its existence.",
    "Large tech companies track and collect data on users, often without proper consent, to use for advertising and profit.",
    "In the 1960s, the CIA was involved in the assassination of leaders in several Latin American countries to protect U.S. interests.",
    "The sugar industry paid scientists in the 1960s to downplay the health risks of sugar and shift the blame to fat consumption.",
    "Oil companies have been known to cover up the environmental damage caused by oil spills and drilling operations.",
    "The U.S. government has been accused of orchestrating or allowing false flag operations to justify military interventions in foreign countries.",
    "During the Cold War, the U.S. and USSR both conducted secret mind control experiments on their own citizens.",
    "Big tech companies like Facebook and Google are known to manipulate algorithms in ways that can influence political outcomes.",
    "The banking industry was deeply involved in the 2008 global financial crisis and received massive bailouts while ordinary people suffered.",
    "In the 1980s, a top U.S. official secretly sold arms to Iraq during their war with Iran while publicly condemning the country.",
    "Pharmaceutical companies have been caught covering up side effects and risks of drugs to protect their profits.",
    "The U.S. government once spied on peaceful civil rights leaders, including Martin Luther King Jr., with the intent to discredit them.",
    "There have been numerous cases where corporations knowingly sold dangerous products to consumers for profit, including asbestos and lead paint.",
    "Governments around the world have been involved in surveillance programs that collect private data on citizens without their consent.",
    "Big corporations often manipulate consumer behavior through targeted advertising that takes advantage of psychological weaknesses.",
    "The tobacco industry was once involved in suppressing evidence about the dangers of secondhand smoke and actively worked to discredit scientists.",
    "Several countries have been caught smuggling weapons and aid to foreign governments or rebel groups in exchange for economic or political favors.",
    "Some large corporations use loopholes in tax laws to avoid paying their fair share, contributing to global inequality.",
    "The U.S. government has engaged in covert operations to overthrow foreign governments that were unfriendly to American corporate interests.",
    "Several high-profile financial institutions were involved in insider trading and fraud, leading to a loss of trust in the banking system.",
    "There are conspiracy theories about the moon landing being staged, but the U.S. government has worked hard to suppress these ideas.",
    "The CIA has been implicated in the creation and funding of various rebel groups around the world for strategic political purposes.",
    "The fast food industry is often criticized for its exploitative labor practices and harmful impact on public health.",
    "The U.S. military has been involved in numerous covert operations that have resulted in the deaths of civilians, all in the name of protecting U.S. interests."
    "World War I was triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary, but the war had long-lasting political and military tensions behind it.",
    "World War II began after Germany invaded Poland in 1939, but the roots of the conflict go back to the harsh terms imposed on Germany by the Treaty of Versailles.",
    "The Vietnam War lasted nearly two decades and saw the involvement of both the U.S. and the Soviet Union, yet it ended in a defeat for the U.S.",
    "The Cold War was not a direct military conflict but was marked by proxy wars, espionage, and the threat of nuclear weapons between the U.S. and the Soviet Union.",
    "The Korean War, which occurred between 1950 and 1953, ended in an armistice, but no official peace treaty was signed, leaving North and South Korea technically still at war.",
    "The Gulf War in 1990-1991 was triggered by Iraq’s invasion of Kuwait, leading to a U.S.-led coalition force liberating Kuwait in just six weeks.",
    "The American Civil War, which lasted from 1861 to 1865, was fought primarily over the issues of slavery and states' rights, ultimately leading to the abolition of slavery in the U.S.",
    "The Napoleonic Wars, fought between 1803 and 1815, were a series of conflicts involving Napoleon Bonaparte's French Empire against various European coalitions.",
    "The Crusades were a series of religious wars during the medieval period, primarily between Christians and Muslims, with the goal of reclaiming Jerusalem and the Holy Land.",
    "The Holocaust occurred during World War II and was one of the darkest chapters in history, with Nazi Germany systematically murdering six million Jews, along with millions of other victims.",
    "The Battle of Stalingrad, fought between Nazi Germany and the Soviet Union during World War II, marked a turning point in the war and is considered one of the bloodiest battles in history.",
    "The U.S. dropped two atomic bombs on Japan in 1945, effectively bringing an end to World War II but raising questions about the ethical use of nuclear weapons.",
    "The Falklands War in 1982 was a brief but intense conflict between the United Kingdom and Argentina over the disputed Falkland Islands.",
    "The Spanish Civil War, fought from 1936 to 1939, was a precursor to World War II, with fascists led by Francisco Franco defeating republican forces backed by communists and anarchists.",
    "The War of 1812 between the United States and the United Kingdom was fought over maritime issues, trade restrictions, and territorial expansion, and ended in a stalemate.",
    "The Russian Revolution of 1917 led to the collapse of the Russian Empire and the rise of the Soviet Union, significantly altering the course of the 20th century.",
    "The Battle of Waterloo in 1815 marked the end of Napoleon Bonaparte’s rule and the Napoleonic Wars, leading to the restoration of European monarchies.",
    "The Vietnam War is often cited as the first 'television war,' with graphic images and coverage influencing public opinion and protests in the U.S.",
    "The Seven Years' War, fought between 1756 and 1763, is considered the first 'world war' due to the involvement of multiple global powers, including Britain, France, Spain, and Prussia.",
    "The Trojan War, though debated by historians, is a famous mythological conflict between the Greeks and the Trojans, allegedly caused by the abduction of Helen of Troy.",
    "The Cold War arms race saw both the U.S. and the Soviet Union developing nuclear weapons, leading to the constant threat of global annihilation.",
    "The U.S. involvement in the Korean War was largely influenced by the policy of containment, aimed at preventing the spread of communism in Asia.",
    "The U.S. War on Terror, initiated after the September 11, 2001 attacks, led to military interventions in Afghanistan and Iraq, with ongoing consequences for international politics.",
    "The Battle of Gettysburg in 1863 was a decisive turning point in the American Civil War, marking the first major defeat for General Robert E. Lee's Confederate Army.",
    "The Suez Crisis of 1956 saw Egypt nationalizing the Suez Canal, leading to a military intervention by the United Kingdom, France, and Israel, and highlighting the decline of British imperial power.",
    "The Mexican-American War, fought between 1846 and 1848, resulted in the U.S. acquiring a vast amount of territory, including California, Arizona, New Mexico, and Texas.",
    "The Opium Wars in the mid-19th century were fought between China and the United Kingdom over the British trade of opium, resulting in China's defeat and the signing of the Treaty of Nanking.",
    "The Iran-Iraq War, lasting from 1980 to 1988, was one of the longest conventional wars of the 20th century, with no decisive victory and massive casualties on both sides.",
    "The War on Drugs, initiated by the U.S. government in the 1980s, led to increased militarization of police forces and controversial interventions in Latin America.",
    "The Peloponnesian War (431-404 BCE) was a long and destructive conflict between Athens and Sparta, with Sparta eventually emerging victorious, but the Greek world severely weakened.",
    "The Hundred Years' War, fought between England and France from 1337 to 1453, was a series of conflicts over territorial disputes and claims to the French throne.",
    "The American Revolutionary War, which lasted from 1775 to 1783, resulted in the formation of the United States after the 13 colonies won independence from Great Britain.",
    "The War of the Roses, fought between the houses of Lancaster and York, was a series of English civil wars between 1455 and 1487 for control of the throne of England.",
    "The Battle of the Somme in 1916 was one of the bloodiest battles in World War I, resulting in over a million casualties and highlighting the horrific toll of trench warfare.",
    "The Boer War (1899-1902) in South Africa saw the British Empire fighting Dutch-descended Boer settlers, resulting in the consolidation of British control in the region.",
    "The Gulf of Tonkin incident in 1964 was used as a pretext for the escalation of U.S. military involvement in Vietnam, but its legitimacy has been questioned.",
    "The Battle of Midway, fought in 1942 during World War II, was a crucial naval battle that turned the tide of the Pacific War in favor of the United States against Japan.",
    "The War in Afghanistan, which began in 2001, was the longest war in U.S. history, with the U.S. military finally withdrawing in 2021 after nearly 20 years of conflict.",
    "The Civil War in Syria, which began in 2011, has involved multiple foreign interventions and is one of the most complex and devastating wars of the 21st century.",
    "The Battle of Verdun, fought between France and Germany in 1916, was one of the longest and most grueling battles of World War I, lasting 10 months and causing hundreds of thousands of casualties.",
    "The U.S. intervention in Panama in 1989, called Operation Just Cause, aimed at overthrowing Panamanian leader Manuel Noriega and restoring democratic governance.",
    "The Bosnian War (1992-1995) was marked by ethnic cleansing and mass atrocities, particularly the Srebrenica massacre, where thousands of Bosnian Muslims were killed.",
    "The Spanish-American War in 1898 was fought over the independence of Cuba from Spain, resulting in the U.S. acquiring the Philippines, Puerto Rico, and Guam.",
    "The Rwandan Genocide in 1994, although not a traditional war, was an ethnic conflict that led to the mass slaughter of Tutsi people by the Hutu-led government.",
    "The Iran-Contra affair in the 1980s involved the illegal sale of arms to Iran by the U.S. government, with profits used to fund Contra rebels in Nicaragua, which led to a political scandal."
    "The first public school in the United States was established in Boston in 1635.",
    "In Japan, students clean their classrooms every day as part of their school routine.",
    "The word 'school' comes from the Greek word 'scholē,' meaning 'leisure' or 'free time.'",
    "In Finland, students don’t start school until they are seven years old, which is later than most countries.",
    "The longest school day in the world is in South Korea, where students can be in school for up to 16 hours.",
    "The first university in the world is the University of Al Quaraouiyine in Morocco, founded in 859 AD.",
    "In some parts of China, students take part in intense 'final exams' that can determine their future career paths.",
    "Albert Einstein was a slow learner in school and struggled with traditional education methods.",
    "In some countries, students wear uniforms to school, which can range from formal to casual depending on the culture.",
    "In Germany, students who attend 'Gymnasium' are on a path toward higher education, while others may choose vocational training.",
    "The largest school in the world by student enrollment is the City Montessori School in India, with over 50,000 students.",
    "In the United States, the average teacher's salary is about $58,000, though it varies by state and district.",
    "The concept of a 'summer vacation' began in the 19th century to give children time to work on family farms.",
    "The first schools in ancient Greece were called 'Academies,' and they were places of philosophical study.",
    "A typical school bus in the U.S. can carry around 72 students at once.",
    "In the United Kingdom, students take national exams called GCSEs, which determine their future educational path.",
    "There are more than 120 million children worldwide who are not enrolled in school, most of them in developing countries.",
    "In Sweden, students receive free lunches in school, and they are provided with healthy, nutritious meals.",
    "The oldest school in the world is the 'University of Al Quaraouiyine' in Morocco, established in 859 AD.",
    "Homework was invented by Roberto Nevilis in 1905 to help students learn more effectively outside of class.",
    "In the early 20th century, many schools used the 'Spelling Bee' to teach vocabulary, which continues to be a popular event today.",
    "The first school system in the world was founded in ancient Mesopotamia around 2000 BC.",
    "The average student spends about 6 hours per day in school during the school year.",
    "In Australia, 'prep' is the first year of schooling, and students typically start school at the age of five.",
    "In South Korea, students often attend 'hagwons,' which are after-school academies for additional learning.",
    "The concept of 'home schooling' has been around for centuries, with some famous historical figures like Thomas Edison being home-schooled.",
    "Many schools across the globe have adopted technology such as tablets and computers to aid in education, though it varies by country.",
    "In some countries like Finland, there is less emphasis on standardized testing, focusing more on project-based learning and creativity.",
    "The longest-running school in the U.S. is the University of North Carolina at Chapel Hill, founded in 1789.",
    "The first co-educational school was founded in the 1830s in the United States, although co-education was controversial at the time.",
    "School cafeterias were first introduced in the United States in the late 19th century to provide students with healthy meals during the school day.",
    "In France, students typically start school at the age of 3, and education is compulsory until the age of 16.",
    "In some countries, like Singapore, school uniforms are designed to minimize distractions and promote equality among students.",
    "The first school bell was invented by Joseph Henry in 1843 and was originally used to signal the start and end of school days.",
    "The United States spends more on education than any other country in the world, with the average cost per student exceeding $12,000 per year.",
    "In countries like Japan and South Korea, students are often ranked in class based on their academic performance, which can affect their future opportunities.",
    "Some schools have a tradition of celebrating 'Pi Day' on March 14 (3/14) to honor the mathematical constant pi.",
    "In 1917, the United States introduced the idea of 'high school' as an institution designed to prepare students for higher education.",
    "In the early 20th century, the first kindergartens were established to provide children with a learning environment before entering formal schooling.",
    "The first written school rules were established in ancient Mesopotamia, where students were expected to behave respectfully toward teachers.",
    "Many schools in Nordic countries have embraced 'play-based learning' to encourage creativity and social development in young children.",
    "The first-ever school yearbook was published at the University of Virginia in 1825.",
    "Some schools have adopted a four-day school week to save on operational costs, although this is controversial.",
    "In the 16th century, education was often reserved for the wealthy, while the majority of children worked to support their families.",
    "The first school for the deaf was founded in Paris in 1760, which revolutionized education for those with hearing impairments.",
    "In some countries like India, students in rural areas have to walk long distances to attend school, with some walking several miles each day.",
    "In Japan, students are responsible for cleaning their classrooms as part of a daily routine, promoting discipline and responsibility.",
    "In the United States, September is National School Success Month, a time to celebrate student achievement and educational milestones.",
    "Some schools have introduced mindfulness programs to help students manage stress and improve their focus and well-being.",
    "The idea of a 'school principal' was first introduced in the 1800s as the head of the school's operations and academics.",
    "In the UK, 'school spirit' and traditions such as school uniforms, sports days, and school plays play a significant role in student culture.",
    "In ancient Rome, children were taught basic subjects like reading, writing, and math, but only the wealthy had access to formal education.",
    "The first female university in the world was founded in 1849 in Turkey, providing women with an opportunity for higher education.",
    "In some countries, such as the Netherlands, students are allowed to choose their subjects as early as high school, based on their career interests.",
    "In Canada, students are taught in both English and French in many provinces, especially in Quebec, as part of the country's bilingual policy.",
    "Some schools have 'no homework' policies in place, allowing students to focus more on physical activities and socializing.",
    "The first school field trip occurred in the 19th century when teachers took their students to museums and cultural sites.",
    "In many countries, students have summer vacations that last for several months, while in others, the school year is divided into shorter terms."
    "Honey never spoils, and archaeologists have found pots of honey in ancient tombs that are still edible.",
    "The world’s most expensive coffee, Kopi Luwak, is made from beans that have been eaten and excreted by civet cats.",
    "The smell of freshly-baked bread can increase sales in a bakery by up to 30%.",
    "Chocolate was once used as currency by the ancient Mayans and Aztecs.",
    "There are over 7,500 different types of apples grown around the world.",
    "Ketchup was once sold as medicine in the 1830s to treat indigestion and diarrhea.",
    "Avocados are technically a fruit, not a vegetable, and belong to the berry family.",
    "Cucumbers are actually 96% water, making them one of the most hydrating foods.",
    "Carrots were originally purple, not orange, until the Dutch cultivated orange carrots in the 17th century.",
    "Watermelons are made up of about 92% water, which makes them incredibly hydrating.",
    "The longest pizza ever made measured 1.15 miles long and was created in Italy in 2012.",
    "Potatoes were the first vegetable to be grown in space, aboard the Space Shuttle Columbia in 1995.",
    "The fruit that has the most protein per calorie is guava.",
    "Chewing gum was originally made from tree sap, particularly chicle from the sapodilla tree.",
    "The average American consumes about 18 acres of pizza in their lifetime.",
    "The most expensive spice in the world is saffron, which comes from the flower of the crocus plant.",
    "Apples float on water because they are 25% air.",
    "The world’s largest chocolate bar weighed over 12,000 pounds and was made in Armenia in 2012.",
    "In Japan, square watermelons are grown for easy storage and transportation.",
    "Cinnamon is made from the inner bark of a tree native to Sri Lanka, and it has been used for thousands of years as both food and medicine.",
    "Tomatoes were once thought to be poisonous in Europe and were grown as ornamental plants.",
    "A single cup of coffee can contain up to 1,000 different chemical compounds.",
    "A typical head of cabbage can weigh between 2 and 5 pounds, depending on the variety and growing conditions.",
    "The most commonly consumed fruit in the world is the banana, with more than 100 billion bananas eaten annually.",
    "The reason a hotdog tastes better with mustard is because mustard has a natural compound that enhances the flavor of meats.",
    "Oranges were first cultivated in Southeast Asia and were once considered a luxury item in ancient Europe.",
    "The average American eats about 46 slices of pizza each year.",
    "In ancient Egypt, garlic was used as both food and medicine, and it was so valuable that workers building the pyramids were paid in garlic.",
    "The first packaged snack food was crackers, introduced by the New York Biscuit Company in 1792.",
    "The most consumed beverage in the world, after water, is tea.",
    "Coconut water is naturally isotonic and is a good substitute for sports drinks due to its high potassium content.",
    "Bananas are radioactive because they contain potassium-40, a naturally occurring isotope of potassium.",
    "Eggplants were once considered a toxic plant and were thought to cause madness when eaten in ancient Europe.",
    "Chili peppers get their heat from a chemical compound called capsaicin, which is used in pepper spray for self-defense.",
    "Doughnuts were invented in the 19th century, and they originally had holes to allow for even cooking.",
    "The ancient Romans used garum, a fermented fish sauce, as a common condiment.",
    "The biggest fruit ever recorded was a pumpkin that weighed 2,624.6 pounds, grown in the United States in 2016.",
    "The world’s first potato chip was created in 1853 by chef George Crum in Saratoga Springs, New York.",
    "Coconut oil is the only oil that can be solid at room temperature due to its high saturated fat content.",
    "The color of a bell pepper changes as it ripens, with green being unripe, yellow, orange, and then red.",
    "The average American eats about 3,000 calories on Thanksgiving Day alone.",
    "The first instant ramen was created by Momofuku Ando in 1958, and it is now a global staple.",
    "The avocado was originally called the 'alligator pear' due to its green, bumpy skin.",
    "Pineapple contains an enzyme called bromelain, which can break down proteins, making it an excellent meat tenderizer.",
    "In 2014, the world’s most expensive pizza was sold in Italy for $12,000, featuring toppings like caviar and truffles.",
    "The average person eats over 35 pounds of cheese each year, with the most popular type being mozzarella.",
    "Vanilla is the second most expensive spice in the world, after saffron, due to the labor-intensive process of pollination and harvesting.",
    "Lettuce was first cultivated by the ancient Egyptians, and it was originally grown for its seeds, not its leaves.",
    "The first commercial breakfast cereal was introduced in 1863 by Dr. John Harvey Kellogg.",
    "The most expensive burger in the world costs over $5,000 and includes ingredients like wagyu beef and gold leaf.",
    "Ginger has been used for centuries as both a spice and a medicinal herb, particularly in traditional Asian medicine.",
    "Olives are technically a fruit, and they are used to make olive oil, which is a staple in Mediterranean cuisine.",
    "The most consumed fruit in the world is the banana, with more than 100 billion bananas eaten annually.",
    "The first candy bar was invented in 1847 by Joseph Fry, who added cocoa butter to his chocolate mix, creating a solid chocolate treat.",
    "In Italy, there’s a specific rule that says pizza should not have pineapple as a topping—it's considered 'blasphemy.'",
    "Cheese is one of the oldest and most diverse foods in the world, with over 1,000 different types produced worldwide.",
    "Potatoes were the first vegetable to be grown in space, aboard the Space Shuttle Columbia in 1995.",
    "The first microwave oven was invented by Percy Spencer in 1945, and it was initially large and expensive.",
    "Pistachios are not only a popular snack but also one of the oldest cultivated nuts in history, dating back to 7000 BC.",
    "Black pepper was once so valuable that it was used as currency in some parts of the world during the Middle Ages.",
    "The potato famine in Ireland in the 19th century led to the mass migration of Irish people to countries like the United States and Canada."
]


# To track which fact was last sent
index = 0

@app.get("/next-fact")
def get_next_fact():
    """Returns the next fact in the list"""
    global index
    if index >= len(facts):
        index = 0  # Reset when all facts are sent
    fact = facts[index]
    index += 1
    return {"fact": fact}

# Run the API using:
# uvicorn api:app --reload
